module.exports = {
  dependencyTypes: [
    'dev',
    'prod',
    'peer',
    'pnpmOverrides',
    'resolutions',
    'local',
    'overrides',
  ],
  filter: '^(?!(@finch-cloud/|eslint-config-base)).*',
  indent: '  ',
  semverGroups: [],
  semverRange: '',
  sortAz: [
    'contributors',
    'dependencies',
    'devDependencies',
    'keywords',
    'peerDependencies',
    'resolutions',
    'scripts',
  ],
  sortFirst: ['name', 'description', 'version', 'author'],
  source: [],
  versionGroups: [],
};
